# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # use ubuntu install provided by vagrant
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "ubuntu/trusty64" 

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.gui = true
  end

  config.ssh.password = "vagrant"
  config.ssh.insert_key = true

  # Second network adapter for EPICS network
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision "shell", inline: "sudo apt-get install -y ubuntu-desktop virtualbox-guest-dkms virtualbox-guest-x11"
  config.vm.provision "shell", inline: "sudo sed -i 's/allowed_users=.*$/allowed_users=anybody/' /etc/X11/Xwrapper.config"

  #config.vm.provision "shell", path: "../common/install_epics.sh", privileged:false, args: "/vagrant/EPICS eth1"
  #config.vm.provision "shell", path: "../common/install_nicos_ubuntu.sh", privileged:false, args: "/vagrant/NICOS"
  #config.vm.provision "shell", path: "../common/install_nicos_ubuntu.sh", privileged:false, args: "/vagrant/NICOS"
  #config.vm.provision "shell", path: "../common/install_pycharm.sh", privileged:false
end